In [1]:
import torch
from multimodal import *

In [2]:
# Gaussian

data = torch.utils.data.DataLoader(GuassianClassification(3, 2, 10, noise=0.01), batch_size=5)
(x,l) = next(iter(data))
print (x.shape, l.shape)

data = torch.utils.data.DataLoader(GuassianClassificationJIT(3, 2, 10, noise=0.01), batch_size=5)
(x,l) = next(iter(data))
print (x.shape, l.shape)

torch.Size([5, 10]) torch.Size([5, 1])
torch.Size([5, 10]) torch.Size([5, 1])


In [8]:
# Multinouli

dataset = MultinouliClassification(3, 2, 10, noise=0)
data = torch.utils.data.DataLoader(dataset, batch_size=5)
(x,l) = next(iter(data))
print (x.shape, l.shape)
print (x)
print (dataset.archetypes)
print (l)

print ("\n------------------------------\n")

dataset = MultinouliClassificationJIT(3, 2, 10, noise=0)
data = torch.utils.data.DataLoader(dataset, batch_size=5)
(x,l) = next(iter(data))
print (x.shape, l.shape)
print (x)
print (dataset.archetypes)
print (l)

print ("\n------------------------------\n")

dataset = MultinouliClassification(3, 2, 10, noise=0.1)
data = torch.utils.data.DataLoader(dataset, batch_size=5)
(x,l) = next(iter(data))
print (x.shape, l.shape)
print (x)
print (dataset.archetypes)
print (l)

print ("\n------------------------------\n")

dataset = MultinouliClassification(3, 2, 10)
data = torch.utils.data.DataLoader(dataset, batch_size=5)
(x,l) = next(iter(data))
print (x.shape, l.shape)
print (x)
print (dataset.archetypes)
print (l)

torch.Size([5, 10]) torch.Size([5, 1])
tensor([[1., 0., 1., 0., 1., 1., 0., 1., 1., 0.],
        [1., 0., 1., 1., 1., 1., 0., 1., 0., 0.],
        [1., 1., 0., 1., 0., 1., 1., 0., 0., 1.],
        [1., 1., 1., 1., 0., 1., 1., 0., 0., 1.],
        [0., 1., 0., 1., 1., 0., 1., 0., 1., 1.]])
tensor([[1., 0., 1., 0., 1., 1., 0., 1., 1., 0.],
        [1., 0., 1., 1., 1., 1., 0., 1., 0., 0.],
        [1., 1., 0., 1., 0., 1., 1., 0., 0., 1.],
        [1., 1., 1., 1., 0., 1., 1., 0., 0., 1.],
        [0., 1., 0., 1., 1., 0., 1., 0., 1., 1.],
        [0., 0., 0., 1., 1., 0., 0., 0., 1., 0.]])
tensor([[0.],
        [1.],
        [2.],
        [0.],
        [1.]])

------------------------------

torch.Size([5, 10]) torch.Size([5, 1])
tensor([[1., 1., 0., 0., 1., 0., 0., 1., 0., 1.],
        [1., 1., 0., 0., 0., 1., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0., 1., 0., 1., 0.],
        [1., 1., 0., 0., 0., 1., 1., 0., 0., 0.],
        [1., 1., 0., 0., 0., 1., 1., 0., 0., 0.]])
tensor([[0., 1.